### ISSUE TITLE
Sayitda titlelarga style berishda hatoliklar bor

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/job-listing-selfmade#2]
https://github.com/MIRZOULUGBEK9008/job-listing-selfmade/blob/a08312fd12f03b832df276211460b491c9eb04bd/index.html#L108
bu linkga hover holatini berishda xatolik bor
sizda:https://prnt.sc/r2rrbioqkcZM
maketda:https://prnt.sc/8nsZn2127zvx

**Comment by MIRZOULUGBEK9008** [comment]
#fix
